# Uncomment the next line to define a global platform for your projecti
# platform :ios, '9.0'

target 'DayDream' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
    pod 'AFNetworking'
    pod 'YYCache'
    pod 'Masonry'
    pod 'EasyReact'
    pod "MWPhotoBrowser"
    pod 'SDWebImage'
    pod 'FontAwesomeKit'
    pod 'MJExtension'
    pod 'IQKeyboardManager'
  # Pods for DayDream

end
